name: Bookinfo

on:
  pull_request:
    paths:
    - 'samples/bookinfo/src/*'
    - '.github/workflows/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup k8s cluster
      uses: engineerd/setup-kind@v0.1.0
    - name: Build Reviews
      run: |
        sha=${GITHUB_SHA:0:7}
        app="${GITHUB_REPOSITORY#*/}"
        cd $GITHUB_WORKSPACE/samples/bookinfo/src/reviews && gradle build
        docker build -t reviews:$sha $GITHUB_WORKSPACE/samples/bookinfo/src/reviews/reviews-wlpcfg
        kind load docker-image reviews:$sha
    - name: Deploy Reviews
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        sha=${GITHUB_SHA:0:7} && app="${GITHUB_REPOSITORY#*/}" && kubectl create deployment reviews --image=reviews:$sha --dry-run -o yaml | kubectl apply -f -
        kubectl expose deployment reviews --port=9080
    - name: Build Productpage
      run: |
        sha=${GITHUB_SHA:0:7}
        app="${GITHUB_REPOSITORY#*/}"
        docker build -t productpage:$sha $GITHUB_WORKSPACE/samples/bookinfo/src/productpage
        kind load docker-image productpage:$sha
    - name: Deploy Productpage
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        sha=${GITHUB_SHA:0:7} && app="${GITHUB_REPOSITORY#*/}" && kubectl create deployment productpage --image=productpage:$sha --dry-run -o yaml | kubectl apply -f -
        kubectl expose deployment productpage --port=9080
    - name: Build Ratings
      run: |
        sha=${GITHUB_SHA:0:7}
        app="${GITHUB_REPOSITORY#*/}"
        docker build -t ratings:$sha $GITHUB_WORKSPACE/samples/bookinfo/src/ratings
        kind load docker-image ratings:$sha
    - name: Deploy Ratings
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        sha=${GITHUB_SHA:0:7} && app="${GITHUB_REPOSITORY#*/}" && kubectl create deployment ratings --image=ratings:$sha --dry-run -o yaml | kubectl apply -f -
        kubectl expose deployment ratings --port=9080
    - name: Build Details
      run: |
        sha=${GITHUB_SHA:0:7}
        app="${GITHUB_REPOSITORY#*/}"
        docker build -t details:$sha $GITHUB_WORKSPACE/samples/bookinfo/src/details
        kind load docker-image details:$sha 
    - name: Deploy Details
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        sha=${GITHUB_SHA:0:7} && app="${GITHUB_REPOSITORY#*/}" && kubectl create deployment details --image=details:$sha --dry-run -o yaml | kubectl apply -f -
        kubectl expose deployment details --port=9080
    - name: Sleep for 60 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'
    - name: Check
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        kubectl get pods --all-namespaces
        kubectl get pods -o yaml
        kubectl get svc --all-namespaces
        kubectl exec -it $(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}') -c ratings -- curl productpage:9080/productpage | grep -o "<title>.*</title>"
        kubectl exec -it $(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}') -c ratings -- curl productpage:9080/productpage | grep -o "William Shakespeare"
        kubectl exec -it $(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}') -c ratings -- curl productpage:9080/productpage | grep -o "Reviewer1"
#     - name: Deploy Bookinfo
#       run: |
#         export KUBECONFIG="$(kind get kubeconfig-path)"
#         kubectl apply -f $GITHUB_WORKSPACE/samples/bookinfo/platform/kube/bookinfo.yaml
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
